# set tabs to num 1 instead of 0 start index



set -g base-index 1
# vim navigation
set -g mode-keys vi
# clipboard on idfk what this even does
set -g set-clipboard on
# some shit idk
set -g default-terminal "screen-256color"
set -g terminal-overrides ",xterm-256color:Tc"

# set git branch status bar
set -g status-right '#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD)'
#set -g status-right '#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD) | #{cpu_icon} #{cpu_percentage}'

# Plugins 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'
run '~/.tmux/plugins/tpm/tpm'


## nvim  esc slow 

set -g escape-time 10

# Or for tmux >= 2.6

set -sg escape-time 1

# tpm 
# List of plugins
#set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# 
set -g @plugin 'tmux-plugins/tmux-yank'
